xfrm: add missing __rcu annotation to nlsk
The nlsk field in struct netns_xfrm is RCU-protected, as evidenced by
the use of rcu_assign_pointer() and RCU_INIT_POINTER() when updating it.
However, the field lacks the __rcu annotation, and most read-side
accesses don't use rcu_dereference().

Add the missing __rcu annotation and convert all read-side accesses to
use rcu_dereference() for correctness and to silence sparse
warnings.

Sparse warning reported my NIPA test (make C=2 net/xfrm/):
net/xfrm/xfrm_user.c:1574:29: error: incompatible types in comparison
expression (different address spaces):
net/xfrm/xfrm_user.c:1574:29:    struct sock [noderef] __rcu *
net/xfrm/xfrm_user.c:1574:29:    struct sock *

Signed-off-by: Antony Antony <antony.antony@secunet.com>