net: missing exported symbols
ERROR: modpost: "sch_direct_xmit" [net/netfilter/nf_flow_table.ko] undefined!
ERROR: modpost: "__qdisc_run" [net/netfilter/nf_flow_table.ko] undefined!
ERROR: modpost: "dev_hard_start_xmit" [net/netfilter/nf_flow_table.ko] undefined!
ERROR: modpost: "netdev_core_pick_tx" [net/netfilter/nf_flow_table.ko] undefined!