xfrm/xfrm_output.c:  fix
net/xfrm/xfrm_output.c:858:25: error: too few arguments to function 'xfrm_get_inner_ipproto'
  858 |                         xfrm_get_inner_ipproto(iter);

net/xfrm: IPsec tunnel mode fix inner_ipproto setting in sec_path
[ Upstream commit 45a98ef4922def8c679ca7c454403d1957fe70e7 ]

fix pulled from stable